name: Build

on:
  schedule:
    # Every day at 9AM EST
    - cron:  '0 13 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
            docker build --tag deephaven-examples/sentiment-analysis .
            docker-compose up -d
      - name: Run Python script
        uses: ./.github/actions/run-python-script
        with:
          script-paths: ./python-scripts/read_rss_default_analysis.py,./python-scripts/read_rss_custom_analysis.py,./python-scripts/queries.py
          host: localhost
      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@v1
        with:
          table-names: built_in_sia,averages,medians,deviations,positive_percent,custom_sia
          host: localhost
